name: Trigger Tests in repo1

on:
  pull_request:
    branches:
      - master  # Укажите ветку, на которую будет направлен PR

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  docker:
    uses: bezsliozniy/swap-api-tests/.github/workflows/run-tests.yml@master
